import React, { createContext, useContext } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
    return context;
};

export const translations = {
    en: {
        dashboard: "Dashboard", analytics: "Analytics", masterData: "Master Data",
        crm: "CRM", sales: "Sales", production: "Production", inventory: "Inventory",
        quality: "Quality", purchasing: "Purchasing", supplyChain: "Supply Chain",
        projects: "Projects", finance: "Finance", reports: "Reports",
        maintenance: "Maintenance", hrPayroll: "HR & Payroll", zatca: "ZATCA E-Invoice",
        approvals: "Approvals", adminCenter: "Admin Center", fixedAssets: "Fixed Assets",
        assetVerification: "Asset Verification", assetLifecycle: "Asset Lifecycle",
        depreciationReports: "Depreciation Reports", costing: "Costing",
        notifications: "Notifications", assetScanner: "Asset Scanner",
        new: "New", create: "Create", edit: "Edit", delete: "Delete", save: "Save",
        cancel: "Cancel", close: "Close", search: "Search", filter: "Filter",
        export: "Export", print: "Print", download: "Download", upload: "Upload",
        refresh: "Refresh", submit: "Submit", approve: "Approve", reject: "Reject",
        send: "Send", back: "Back", next: "Next", previous: "Previous",
        viewAll: "View All", markAllRead: "Mark all read",
        active: "Active", inactive: "Inactive", pending: "Pending", approved: "Approved",
        rejected: "Rejected", completed: "Completed", cancelled: "Cancelled",
        draft: "Draft", inProgress: "In Progress", overdue: "Overdue", scheduled: "Scheduled",
        code: "Code", name: "Name", description: "Description", date: "Date",
        status: "Status", amount: "Amount", quantity: "Quantity", price: "Price",
        total: "Total", customer: "Customer", vendor: "Vendor", material: "Material",
        product: "Product", location: "Location", department: "Department",
        priority: "Priority", type: "Type",
        materials: "Materials", customers: "Customers", vendors: "Vendors",
        newMaterial: "New Material", newCustomer: "New Customer", newVendor: "New Vendor",
        materialCode: "Material Code", materialName: "Material Name",
        materialType: "Material Type", unitOfMeasure: "Unit of Measure",
        unitPrice: "Unit Price", unitCost: "Unit Cost", currentStock: "Current Stock",
        reorderPoint: "Reorder Point", downloadTemplate: "Download Template", uploadExcel: "Upload Excel",
        assetNumber: "Asset Number", assetName: "Asset Name", assetTag: "Asset Tag",
        assetClass: "Asset Class", acquisitionDate: "Acquisition Date",
        acquisitionCost: "Acquisition Cost", netBookValue: "Net Book Value",
        accumulatedDepreciation: "Accumulated Depreciation", usefulLife: "Useful Life",
        depreciationMethod: "Depreciation Method", salvageValue: "Salvage Value",
        responsiblePerson: "Responsible Person",
        purchaseRequisition: "Purchase Requisition", rfq: "Request for Quotation",
        purchaseOrder: "Purchase Order", goodsReceiptNote: "Goods Receipt Note",
        vendorInvoice: "Vendor Invoice", threeWayMatch: "3-Way Match",
        quotation: "Quotation", salesOrder: "Sales Order", delivery: "Delivery",
        invoice: "Invoice", salesReturn: "Sales Return",
        productionOrder: "Production Order", bom: "Bill of Materials",
        routing: "Routing", workCenter: "Work Center",
        inspectionLot: "Inspection Lot", qualityControl: "Quality Control",
        nonConformance: "Non-Conformance", capa: "CAPA",
        stockMovement: "Stock Movement", stockTransfer: "Stock Transfer",
        cycleCount: "Cycle Count", stockLevel: "Stock Level",
        unreadNotifications: "Unread Notifications", readNotifications: "Read Notifications",
        noNotifications: "No notifications", notificationSettings: "Notification Settings",
        loading: "Loading...", noData: "No data available", success: "Success",
        error: "Error", warning: "Warning", confirm: "Confirm", areYouSure: "Are you sure?",
        savedSuccessfully: "Saved successfully", deletedSuccessfully: "Deleted successfully",
        operationSuccessful: "Operation successful", operationFailed: "Operation failed",
        companyName: "HORIZON", companyTagline: "Powering Your Digital Future",
        projectsServices: "Projects & Services", activeProjects: "Active Projects",
        revenue: "Revenue", unbilled: "Unbilled", utilization: "Utilization",
        avgMargin: "Avg Margin", atRisk: "At Risk", timesheets: "Timesheets",
        expenses: "Expenses", milestones: "Milestones", invoices: "Invoices", resources: "Resources",
        salesDistribution: "Sales & Distribution", hitRate: "Hit Rate", otif: "OTIF",
        creditHold: "Credit Hold", returns: "Returns", quotations: "Quotations",
        orders: "Orders", deliveries: "Deliveries", services: "Services",
        manufacturing: "Manufacturing & Production", activeProduction: "Active Production",
        avgYield: "Average Yield", availableWorkCenters: "Available Work Centers",
        variancesPending: "Variances Pending", productionOrders: "Production Orders",
        boms: "BOMs", routings: "Routings", workCenters: "Work Centers",
        variances: "Variances", standardCosts: "Standard Costs",
        qualityManagement: "Quality Management", firstPassYield: "First Pass Yield",
        rejectedLots: "Rejected Lots", openNCs: "Open NCs", coasIssued: "COAs Issued",
        inspectionLots: "Inspection Lots", nonConformances: "Non-Conformances",
        coas: "COA", qcPlans: "QC Plans",
        procurement: "Procurement", pendingPRs: "Pending PRs", activePOs: "Active POs",
        totalSpend: "Total Spend", pendingMatches: "Pending Matches",
        requisitions: "Requisitions", rfqs: "RFQs", pos: "Purchase Orders",
        grns: "GRNs", vendorInvoices: "Vendor Invoices",
        maintenanceManagement: "Maintenance Management", openWorkOrders: "Open Work Orders",
        pmCompliance: "PM Compliance", mttr: "MTTR (Hours)", criticalDown: "Critical Down",
        lowStockParts: "Low Stock Parts", totalCost: "Total Cost", workOrders: "Work Orders",
        pmPlans: "PM Plans", equipment: "Equipment", spareParts: "Spare Parts",
        downtimes: "Downtimes", consumptions: "Consumptions",
        financeAccounting: "Finance & Accounting", totalAROutstanding: "Total AR Outstanding",
        totalAPOutstanding: "Total AP Outstanding", overdueAR: "Overdue AR",
        fixedAssetsNBV: "Fixed Assets NBV", gl: "GL", ar: "AR", ap: "AP", cashBank: "Cash/Bank",
        hrPayrollKSA: "HR & Payroll", activeEmployees: "Active Employees",
        saudizationRate: "Workforce Ratio", pendingLeaves: "Pending Leaves",
        activeLoans: "Active Loans", employees: "Employees", leaves: "Leave Requests",
        payroll: "Payroll", loansAdvances: "Loans/Advances", endOfService: "End of Service",
        analyticsBI: "Business Intelligence & Analytics",
        kpisDashboardsInsights: "KPIs, Dashboards & Performance Insights",
        dateRange: "Date Range", branch: "Branch", last7Days: "Last 7 Days",
        last30Days: "Last 30 Days", last90Days: "Last 90 Days", ytd: "Year to Date",
        lastYear: "Last Year", allBranches: "All Branches",
        totalRevenue: "Total Revenue", grossProfit: "Gross Profit", stockValue: "Stock Value",
        margin: "margin", turnover: "turnover", efficiency: "efficiency",
        dso: "DSO (Days)", dsoFull: "Days Sales Outstanding",
        dpo: "DPO (Days)", dpoFull: "Days Payable Outstanding",
        qualityRate: "Quality Rate", revenueTrend: "Revenue Trend (Last 6 Months)",
        topProductsByRevenue: "Top 5 Products by Revenue", inventoryAging: "Inventory Aging",
        arAgingAnalysis: "AR Aging Analysis", totalOrders: "Total Orders",
        avgOrderValue: "Avg Order Value", perOrder: "Per order",
        pendingOrders: "Pending Orders", awaitingConfirmation: "Awaiting confirmation",
        delivered: "Delivered", completedOrders: "Completed orders",
        salesByMonth: "Sales by Month", salesByStatus: "Sales by Status", count: "Count",
        unitsSold: "units sold", totalStockValue: "Total Stock Value", items: "items",
        stockTurnover: "Stock Turnover", annualTurnover: "Annual turnover",
        slowMoving: "Slow Moving", over90Days: ">90 days old", lowStockItems: "Low Stock Items",
        needReorder: "Need reorder", inventoryAgingDistribution: "Inventory Aging Distribution",
        stockValueByCategory: "Stock Value by Category", value: "Value",
        productionEfficiency: "Production Efficiency", outputVsPlanned: "Output vs planned",
        totalProduced: "Total Produced", units: "Units",
        productionByStatus: "Production by Status",
        productionQuantityByProduct: "Production Quantity by Product",
        totalPurchases: "Total Purchases", avgPOValue: "Avg PO Value", perPO: "Per PO",
        payableOutstanding: "Payable outstanding", pendingPOs: "Pending POs",
        awaitingApproval: "Awaiting approval", purchaseByVendor: "Purchase by Vendor",
        apAging: "AP Aging", salesOutstanding: "Sales outstanding",
        revenueVsCosts: "Revenue vs Costs", costs: "Costs", profit: "Profit",
        arVsAp: "AR vs AP", accountsReceivable: "Accounts Receivable",
        accountsPayable: "Accounts Payable", cashFlowIndicators: "Cash Flow Indicators",
        workingCapital: "Working Capital", cashConversionCycle: "Cash Conversion Cycle",
        days: "days", currentRatio: "Current Ratio", quickRatio: "Quick Ratio",
        projectMargin: "Project Margin", grossMargin: "Gross margin",
        employeesByDepartment: "Employees by Department",
        projectPerformance: "Project Performance", complete: "complete",
        newProject: "New Project", newTask: "New Task", newTimesheet: "New Timesheet",
        newExpense: "New Expense", newMilestone: "New Milestone",
        resourceAllocations: "Resource Allocations", projectExpenses: "Project Expenses",
        projectMilestones: "Project Milestones", projectTasks: "Project Tasks",
        allocateResource: "Allocate Resource", bulkAllocate: "Bulk Allocate",
        aiAssistantAnalytics: "AI Assistant & Analytics",
        aiInsightsDesc: "Get insights, ask questions, and let AI help you manage your business",
        chatAssistant: "Chat Assistant", aiInsights: "AI Insights", newChat: "New Chat",
        erpAssistant: "ERP Assistant", messages: "messages",
        howCanIHelp: "How can I help you today?",
        askMeAnything: "Ask me anything about your business data, reports, or let me help you create and manage records.",
        showSalesPerformance: "Show sales performance",
        checkInventoryLevels: "Check inventory levels",
        viewPendingApprovals: "View pending approvals",
        askAnything: "Ask me anything about your business...",
        noConversationSelected: "No conversation selected",
        createChatToStart: "Create a new chat to get started", startNewChat: "Start New Chat",
        kpiDashboard: "KPI Dashboard",
        trackMonitorKPIs: "Track and monitor key performance indicators",
        addKPI: "Add KPI", onTarget: "On Target", offTarget: "Off Target",
        avgAchievement: "Avg Achievement", ofKPIs: "of KPIs",
        needsAttention: "Needs attention", requiresAction: "Requires action",
        overallPerformance: "Overall performance", allKPIs: "All KPIs",
        allCategories: "All Categories", financialKPIs: "Financial KPIs",
        operationalKPIs: "Operational KPIs", customerKPIs: "Customer KPIs",
        employeeKPIs: "Employee KPIs", qualityKPIs: "Quality KPIs",
        supplyChainKPIs: "Supply Chain KPIs", kpiName: "KPI Name", category: "Category",
        owner: "Owner", target: "Target", actual: "Actual", achievement: "Achievement",
        trend: "Trend", updateFreq: "Update Freq",
        masterDataMgmt: "Master Data Management",
        manageMasterData: "Manage materials, customers, vendors, salesmen & hierarchies",
        refreshAll: "Refresh All", totalMaterials: "Total Materials", groups: "groups",
        totalCustomers: "Total Customers", salesmen: "Salesmen",
        unitConversions: "Unit Conversions", multiUOM: "Multi-UOM enabled",
        materialsItems: "Materials & Items Master", template: "Template",
        excelUpload: "Excel Upload", customerMaster: "Customer Master",
        vendorMaster: "Vendor Master", salesmenMaster: "Salesmen Master",
        newSalesman: "New Salesman", materialGroups: "Material Groups", newGroup: "New Group",
        materialSubGroups: "Material Sub-Groups", newSubGroup: "New Sub-Group",
        unitConversionsTitle: "Unit Conversions", newConversion: "New Conversion",
        coilManagementSlitting: "Coil Management & Slitting",
        trackCoilsDesc: "Track and manage raw material coils and slitting operations",
        totalCoils: "Total Coils", allRegisteredCoils: "All registered coils",
        available: "Available", readyToUse: "Ready to use", totalWeight: "Total Weight",
        reserved: "Reserved", forProduction: "For production", qcPending: "QC Pending",
        awaitingInspection: "Awaiting inspection", coilInventory: "Coil Inventory",
        slittingOperations: "Slitting Operations", history: "History",
        slitCoil: "Slit Coil", registerCoil: "Register Coil",
        coilHistory: "Coil History & Traceability",
        supplyChainMgmt: "Supply Chain Management",
        endToEndVisibility: "End-to-end visibility of material and product flow",
        distribution: "Distribution", recentPurchaseOrders: "Recent Purchase Orders",
        recentSalesOrders: "Recent Sales Orders",
        costManagement: "Cost Management",
        productCostingDesc: "Product Costing, Variance Analysis & Job Costing",
        activeProductCosts: "Active Product Costs", avgCost: "Avg", unit: "unit",
        totalActualCosts: "Total Actual Costs", costRecords: "cost records",
        unfavorableVariances: "Unfavorable Variances", averageMargin: "Average Margin",
        acrossProducts: "Across", products: "products", productCosts: "Product Costs",
        actualCosts: "Actual Costs", costPools: "Cost Pools", overheadRates: "Overhead Rates",
        jobCosts: "Job Costs", productCosting: "Product Costing",
        calculateProductCost: "Calculate Product Cost",
        actualCostRecords: "Actual Cost Records",
        costVarianceAnalysis: "Cost Variance Analysis",
        newCostPool: "New Cost Pool", newOverheadRate: "New Overhead Rate",
        jobCosting: "Job Costing",
        treasuryMgmt: "Treasury Management",
        cashFlowForecastingDesc: "Cash Flow Forecasting & Liquidity Management",
        assetLifecycleMgmt: "Asset Lifecycle Management",
        trackAssetDisposalDesc: "Track asset disposal, retirement, ROI and lifecycle analytics",
        exportCSV: "Export CSV", printReport: "Print Report", filters: "Filters", reset: "Reset",
        allClasses: "All Classes", machinery: "Machinery", vehicles: "Vehicles",
        computers: "Computers", furniture: "Furniture", disposalType: "Disposal Type",
        allTypes: "All Types", sale: "Sale", scrap: "Scrap", donation: "Donation",
        tradeIn: "Trade-In", writeOff: "Write-Off", dateFrom: "Date From", dateTo: "Date To",
        yearFrom: "Year From", yearTo: "Year To", activeAssets: "Active Assets",
        currentlyInUse: "Currently in use", disposedAssets: "Disposed Assets",
        pendingApproval: "pending approval", disposalValue: "Disposal Value",
        transactions: "transactions", totalGainLoss: "Total Gain/Loss",
        netGain: "Net gain", netLoss: "Net loss", averageROI: "Average ROI",
        onDisposedAssets: "On disposed assets", byType: "By Type", byYear: "By Year",
        roiAnalysis: "ROI Analysis", lifecycle: "Lifecycle", details: "Details",
        disposalByType: "Disposal by Type", breakdown: "Breakdown", assets: "assets",
        disposalTrend: "Disposal Trend by Year", roiDistribution: "ROI Distribution",
        roiCategories: "ROI Categories",
        assetAgeVsMaintenance: "Asset Age vs Maintenance Cost", insights: "Insights",
        disposalTransactions: "Disposal Transactions",
        approvalWorkflowConfig: "Approval Workflow Configuration",
        configureMultiLevelDesc: "Configure multi-level approval chains for business documents",
        workflowBuilder: "Workflow Builder", allRules: "All Rules",
        configureNewWorkflow: "Configure New Workflow", newRule: "New Rule",
        allApprovalMatrixRules: "All Approval Matrix Rules", documentType: "Document Type",
        amountRange: "Amount Range (LKR)", level: "Level", requiredRole: "Required Role",
        settings: "Settings", mandatory: "Mandatory", parallel: "Parallel", notify: "Notify",
        approvalLevels: "Approval Levels", hr: "HR",
        overview: "Overview", financial: "Financial", operational: "Operational",
        employee: "Employee", bomItems: "BOM Items", operations: "Operations",
        materialIssue: "Material Issue", productionConfirmation: "Production Confirmation",
        forecastAccuracy: "Forecast Accuracy", demandForecast: "Demand Forecast",
        forecastMethod: "Forecast Method", forecastedQuantity: "Forecasted Quantity",
        actualDemand: "Actual Demand", cashPosition: "Cash Position",
        cashFlowForecast: "Cash Flow Forecast", liquidityRatio: "Liquidity Ratio",
        inflows: "Inflows", outflows: "Outflows",
        depreciationSchedule: "Depreciation Schedule", assetRegister: "Asset Register",
        monthlyDepreciation: "Monthly Depreciation", yearlyDepreciation: "Yearly Depreciation",
        payslip: "Payslip", attendanceRegister: "Attendance Register",
        leaveBalance: "Leave Balance", endOfServiceBenefit: "End of Service Benefit",
        wps: "WPS", gosi: "EPF/ETF",
        zatcaCompliant: "Tax Compliant", einvoicing: "E-Invoicing", qrCode: "QR Code",
        submissionStatus: "Submission Status", clearanceStatus: "Clearance Status",
        nationalityDistribution: "Nationality Distribution",
        nonSaudi: "Non-local", saudization: "Local Workforce", saudi: "Local",
        riyadh: "Colombo", jeddah: "Kandy", dammam: "Galle", executive: "Executive",
    }
};

export const LanguageProvider = ({ children }) => {
    const language = 'en';
    const isRTL = false;
    const toggleLanguage = () => {};
    const t = (key) => translations.en[key] || key;

    return (
        <LanguageContext.Provider value={{ language, isRTL, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export default LanguageContext;
